Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x_fcn=np.linspace(min(x),max(x));
plt.plot(x,y,'o',label='data')
plt.plot(x,Z@a,label='quadratic fit')
plt.xlabel('x')
plt.ylabel('y')
plt.legend();
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [4], line 3[0m
[1;32m      1[0m x_fcn[38;5;241m=[39mnp[38;5;241m.[39mlinspace([38;5;28mmin[39m(x),[38;5;28mmax[39m(x));
[1;32m      2[0m plt[38;5;241m.[39mplot(x,y,[38;5;124m'[39m[38;5;124mo[39m[38;5;124m'[39m,label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mdata[39m[38;5;124m'[39m)
[0;32m----> 3[0m plt[38;5;241m.[39mplot(x,Z[38;5;129m@a[39m,label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mquadratic fit[39m[38;5;124m'[39m)
[1;32m      4[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m)
[1;32m      5[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'a' is not defined
NameError: name 'a' is not defined

